# Generated by Django 5.2.5 on 2025-11-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userole',
            field=models.CharField(max_length=10),
        ),
    ]
