# Generated by Django 5.2.5 on 2025-11-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_userole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
