# Generated by Django 5.2.5 on 2025-11-12 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userole',
            new_name='userrole',
        ),
    ]
