# Generated by Django 5.2.5 on 2025-11-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_userole_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userrole',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
