# Generated by Django 5.2.5 on 2025-11-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_action', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
