# Generated by Django 5.2.5 on 2025-11-25 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tran_id', models.AutoField(primary_key=True, serialize=False)),
                ('tran_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='userid')),
            ],
        ),
    ]
